# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_converterPlus.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(711, 203)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gl_main = QtWidgets.QGridLayout()
        self.gl_main.setObjectName("gl_main")
        self.gbox_values = QtWidgets.QGroupBox(Form)
        self.gbox_values.setObjectName("gbox_values")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox_values)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gl_values = QtWidgets.QGridLayout()
        self.gl_values.setObjectName("gl_values")
        self.l_val_inp = QtWidgets.QLabel(self.gbox_values)
        self.l_val_inp.setObjectName("l_val_inp")
        self.gl_values.addWidget(self.l_val_inp, 0, 0, 1, 1)
        self.l_val_out = QtWidgets.QLabel(self.gbox_values)
        self.l_val_out.setObjectName("l_val_out")
        self.gl_values.addWidget(self.l_val_out, 1, 0, 1, 1)
        self.ln_val_inp = QtWidgets.QLineEdit(self.gbox_values)
        self.ln_val_inp.setObjectName("ln_val_inp")
        self.gl_values.addWidget(self.ln_val_inp, 0, 1, 1, 1)
        self.ln_val_out = QtWidgets.QLineEdit(self.gbox_values)
        self.ln_val_out.setObjectName("ln_val_out")
        self.gl_values.addWidget(self.ln_val_out, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gl_values, 0, 0, 1, 1)
        self.gl_main.addWidget(self.gbox_values, 1, 0, 1, 1)
        self.gbox_numbers = QtWidgets.QGroupBox(Form)
        self.gbox_numbers.setObjectName("gbox_numbers")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbox_numbers)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gl_numbers = QtWidgets.QGridLayout()
        self.gl_numbers.setObjectName("gl_numbers")
        self.l_num_inp = QtWidgets.QLabel(self.gbox_numbers)
        self.l_num_inp.setObjectName("l_num_inp")
        self.gl_numbers.addWidget(self.l_num_inp, 0, 0, 1, 1)
        self.l_num_out = QtWidgets.QLabel(self.gbox_numbers)
        self.l_num_out.setObjectName("l_num_out")
        self.gl_numbers.addWidget(self.l_num_out, 1, 0, 1, 1)
        self.ln_num_inp = QtWidgets.QLineEdit(self.gbox_numbers)
        self.ln_num_inp.setObjectName("ln_num_inp")
        self.gl_numbers.addWidget(self.ln_num_inp, 0, 1, 1, 1)
        self.ln_num_out = QtWidgets.QLineEdit(self.gbox_numbers)
        self.ln_num_out.setObjectName("ln_num_out")
        self.gl_numbers.addWidget(self.ln_num_out, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gl_numbers, 0, 0, 1, 1)
        self.gl_main.addWidget(self.gbox_numbers, 1, 1, 1, 1)
        self.gl_up = QtWidgets.QGridLayout()
        self.gl_up.setObjectName("gl_up")
        self.btn_hotKeys = QtWidgets.QPushButton(Form)
        self.btn_hotKeys.setObjectName("btn_hotKeys")
        self.gl_up.addWidget(self.btn_hotKeys, 0, 1, 1, 1)
        self.sbox_round = QtWidgets.QSpinBox(Form)
        self.sbox_round.setFrame(False)
        self.sbox_round.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sbox_round.setSuffix("")
        self.sbox_round.setMinimum(1)
        self.sbox_round.setProperty("value", 2)
        self.sbox_round.setObjectName("sbox_round")
        self.gl_up.addWidget(self.sbox_round, 0, 5, 1, 1)
        self.btn_values = QtWidgets.QPushButton(Form)
        self.btn_values.setFlat(False)
        self.btn_values.setObjectName("btn_values")
        self.gl_up.addWidget(self.btn_values, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gl_up.addWidget(self.frame, 0, 4, 1, 1)
        self.gl_main.addLayout(self.gl_up, 0, 0, 1, 2)
        self.btn_conv = QtWidgets.QPushButton(Form)
        self.btn_conv.setObjectName("btn_conv")
        self.gl_main.addWidget(self.btn_conv, 2, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(Form)
        self.btn_clear.setObjectName("btn_clear")
        self.gl_main.addWidget(self.btn_clear, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gl_main, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Converter+"))
        self.gbox_values.setTitle(_translate("Form", " Величины"))
        self.l_val_inp.setText(_translate("Form", "исходные"))
        self.l_val_out.setText(_translate("Form", "конвертируемы"))
        self.gbox_numbers.setTitle(_translate("Form", " Числа"))
        self.l_num_inp.setText(_translate("Form", "исходные"))
        self.l_num_out.setText(_translate("Form", "конвертируемые"))
        self.btn_hotKeys.setText(_translate("Form", "горячие клавиши"))
        self.sbox_round.setPrefix(_translate("Form", "округлить до: "))
        self.btn_values.setText(_translate("Form", "поддерживаемые величины"))
        self.btn_conv.setText(_translate("Form", "конвертировать"))
        self.btn_clear.setText(_translate("Form", "сброс"))

